POLYGON_API_KEY = 'JoxzZp1sWdDw8hcurMKj9OEbSwxwVW_1'

# TODO: BE VERY CAREFUL OF USING THIS REAL ALPACA KEY
ALPACA_KEY_ID = 'AK2EEQJ1Z1QROEGEUP6H'
ALPACA_SECRET_KEY = 'mmnuAC5EZXSuYDZ1VoqBzmg5HvAvKEz6UvvvhJO8'
ALPACA_BASE_URL = 'https://api.alpaca.markets'

PAPER_ALPACA_BASE_URL = 'https://paper-api.alpaca.markets'
PAPER_ALPACA_API_KEY = 'PKOWG3QA1DRMXVANAI32'
PAPER_ALPACA_SECRET_KEY = 'BuydkYxYwu2tc57BMgLWgDz3yjDR5F9L7qVibRtN'